name: protein-uq 
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - torchaudio
  - numpy
  - seaborn
  - pandas
  - scipy
  - torchvision
  - matplotlib
  - scikit-learn
  - cudatoolkit
  - gpytorch
