python active_learning.py --split gb1_1 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy random --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_greedy --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_1 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_2 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_3 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_2 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_5 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model ridge --representation esm --uncertainty ridge --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.1
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.2
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.3
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.4
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty dropout --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.5
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty mve --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty svi --scale --num_folds 3 --al_strategy explorative_sample --num_al_loops 5 --al_topk 100 --mean --dropout 0.0
