python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit_ucb --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy exploit_ts --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split gb1_4 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split aav_7 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model gp --representation esm --uncertainty gp --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty ensemble --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
python active_learning.py --split meltome_1 --model cnn --representation esm --uncertainty evidential --scale --num_folds 3 --al_strategy random --al_topk 1 --mean --dropout 0.0 --al_step_scale single
